{
 "title": "rspamd : Mail Server Email/Spam Statistik",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Scanned",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    { "expr": "rspamd_stats_scanned" }
   ]
  },
  {
   "title": "Scanned",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    { "expr": "rspamd_stats_scanned" }
   ]
  },
  {
   "title": "No Action",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    { "expr": "rspamd_actions_no_action" }
   ]
  },
  {
   "title": "Greylist",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    { "expr": "rspamd_actions_greylist" }
   ]
  },
  {
   "title": "Add Header",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    { "expr": "rspamd_actions_add_header" }
   ]
  },
  {
   "title": "Learned",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    { "expr": "rspamd_stats_learned" }
   ]
  },
  {
   "title": "global %",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rspamd_actions_reject" },
    { "expr": "rspamd_actions_add_header" },
    { "expr": "rspamd_actions_greylist" },
    { "expr": "rspamd_actions_no_action" },
    { "expr": "rspamd_actions_rewrite_subject" },
    { "expr": "rspamd_actions_soft_reject" }
   ]
  },
  {
   "title": "Connections over Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(rspamd_stats_connections[1m])",
     "legendFormat": "connections"
    },
    {
     "expr": "rate(rspamd_stats_control_connections[1m])",
     "legendFormat": "control_connections"
    }
   ]
  },
  {
   "title": "Pools over Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(rspamd_stats_pools_allocated[1m])",
     "legendFormat": "pools_allocated"
    },
    {
     "expr": "rate(rspamd_stats_pools_freed[1m])",
     "legendFormat": "pools_freed"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 17 },
   "format": "short",
   "valueName": "current",
   "targets": [
    { "expr": "rspamd_actions_add_header", "legendFormat": "add_header" },
    { "expr": "rspamd_actions_greylist", "legendFormat": "greylist" },
    { "expr": "rspamd_actions_no_action", "legendFormat": "no_action" },
    { "expr": "rspamd_actions_reject", "legendFormat": "reject" },
    { "expr": "rspamd_actions_rewrite_subject", "legendFormat": "rewrite_subject" },
    { "expr": "rspamd_actions_soft_reject", "legendFormat": "soft_reject" }
   ]
  },
  {
   "title": "Actions",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 4, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rspamd_actions_no_action", "legendFormat": "no_action" },
    { "expr": "rspamd_actions_greylist", "legendFormat": "greylist" },
    { "expr": "rspamd_actions_add_header", "legendFormat": "add_header" },
    { "expr": "rspamd_actions_reject", "legendFormat": "reject" },
    { "expr": "rspamd_actions_rewrite_subject", "legendFormat": "rewrite_subject" },
    { "expr": "rspamd_actions_soft_reject", "legendFormat": "soft_reject" }
   ]
  },
  {
   "title": "Spam over Time",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(rspamd_stats_spam_count[1m])",
     "legendFormat": "spam_count"
    },
    {
     "expr": "rate(rspamd_stats_ham_count[1m])",
     "legendFormat": "ham_count"
    },
    { "expr": "rate(rspamd_stats_learned[1m])", "legendFormat": "stats_learned" }
   ]
  },
  {
   "title": "Chunk over Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(rspamd_stats_chunks_allocated[1m])",
     "legendFormat": "chunks_allocated"
    },
    {
     "expr": "rate(rspamd_stats_chunks_freed[1m])",
     "legendFormat": "chunks_freed"
    },
    {
     "expr": "rate(rspamd_stats_chunks_oversized[1m])",
     "legendFormat": "chunks_oversized"
    }
   ]
  },
  {
   "title": "Actions over Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(rspamd_stats_scanned[1m])", "legendFormat": "scanned" },
    { "expr": "rate(rspamd_stats_learned[1m])", "legendFormat": "learned" },
    {
     "expr": "rate(rspamd_stats_total_learns[1m])",
     "legendFormat": "total_learns"
    }
   ]
  }
 ]
}